language: ruby

before_script: ./bin/build
script: ./bin/test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: script
  script: ./bin/deploy
  on:
    branch: source

sudo: false
